Skip "hexagon-win" container
This build failed, so let's skip it for now.

Details from https://git.codelinaro.org/clo/toolchain-for-hexagon/hexagon-builder/-/jobs/197638/viewer:

     #6 [2/7] RUN cp /etc/apt/sources.list /etc/apt/sources.list~ &&     sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list &&     apt-get -y update &&     DEBIAN_FRONTEND=noninteractive apt install -y make build-essential         wget flex bison unzip python-is-python3 python3-pip         ninja-build pkg-config libpixman-1-dev libglib2.0-dev git wget         curl libelf-dev libvirglrenderer-dev libepoxy-dev libgtk-3-dev         libgcrypt20-dev libgpg-error-dev libzip-dev bash coreutils         git git-lfs libncurses5 mingw-w64 msitools libz-mingw-w64-dev         pkg-config-mingw-w64-x86-64 zstd cmake wine &&     DEBIAN_FRONTEND=noninteractive apt build-dep -yy qemu
     #6 0.515 Ign:1 http://security.ubuntu.com/ubuntu lunar-security InRelease
     #6 0.523 Ign:2 http://archive.ubuntu.com/ubuntu lunar InRelease
     #6 0.668 Err:3 http://security.ubuntu.com/ubuntu lunar-security Release
     #6 0.668   404  Not Found [IP: 185.125.190.82 80]
     #6 0.680 Ign:4 http://archive.ubuntu.com/ubuntu lunar-updates InRelease
     #6 0.836 Ign:5 http://archive.ubuntu.com/ubuntu lunar-backports InRelease
     #6 0.992 Err:6 http://archive.ubuntu.com/ubuntu lunar Release
     #6 0.992   404  Not Found [IP: 185.125.190.82 80]
     #6 1.147 Err:7 http://archive.ubuntu.com/ubuntu lunar-updates Release
     #6 1.147   404  Not Found [IP: 185.125.190.82 80]
     #6 1.303 Err:8 http://archive.ubuntu.com/ubuntu lunar-backports Release
     #6 1.303   404  Not Found [IP: 185.125.190.82 80]
        time="2024-12-14T20:29:53.534673668Z" level=warning msg="failed to read oom_kill event" error="open /sys/fs/cgroup/docker/buildkit/mmfg6c6m67jxktbxgk89uprwe/memory.events: no such file or directory" span="[2/7] RUN cp /etc/apt/sources.list /etc/apt/sources.list~ &&     sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list &&     apt-get -y update &&     DEBIAN_FRONTEND=noninteractive apt install -y make build-essential         wget flex bison unzip python-is-python3 python3-pip         ninja-build pkg-config libpixman-1-dev libglib2.0-dev git wget         curl libelf-dev libvirglrenderer-dev libepoxy-dev libgtk-3-dev         libgcrypt20-dev libgpg-error-dev libzip-dev bash coreutils         git git-lfs libncurses5 mingw-w64 msitools libz-mingw-w64-dev         pkg-config-mingw-w64-x86-64 zstd cmake wine &&     DEBIAN_FRONTEND=noninteractive apt build-dep -yy qemu" spanID=2bcdc133755d7fad traceID=2f5ab7a485a1accdcc76c2b31848b824
    #6 1.307 Reading package lists...
    #6 1.317 E: The repository 'http://security.ubuntu.com/ubuntu lunar-security Release' does not have a Release file.
    #6 1.317 E: The repository 'http://archive.ubuntu.com/ubuntu lunar Release' does not have a Release file.
    #6 1.317 E: The repository 'http://archive.ubuntu.com/ubuntu lunar-updates Release' does not have a Release file.
    #6 1.317 E: The repository 'http://archive.ubuntu.com/ubuntu lunar-backports Release' does not have a Release file.
    #6 ERROR: process "/bin/sh -c cp /etc/apt/sources.list /etc/apt/sources.list~ &&     sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list &&     apt-get -y update &&     DEBIAN_FRONTEND=noninteractive apt install -y make build-essential         wget flex bison unzip python-is-python3 python3-pip         ninja-build pkg-config libpixman-1-dev libglib2.0-dev git wget         curl libelf-dev libvirglrenderer-dev libepoxy-dev libgtk-3-dev         libgcrypt20-dev libgpg-error-dev libzip-dev bash coreutils         git git-lfs libncurses5 mingw-w64 msitools libz-mingw-w64-dev         pkg-config-mingw-w64-x86-64 zstd cmake wine &&     DEBIAN_FRONTEND=noninteractive apt build-dep -yy qemu" did not complete successfully: exit code: 100
        time="2024-12-14T20:29:53.679501773Z" level=error msg=/moby.buildkit.v1.Control/Solve error="rpc error: code = Unknown desc = process \"/bin/sh -c cp /etc/apt/sources.list /etc/apt/sources.list~ &&     sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list &&     apt-get -y update &&     DEBIAN_FRONTEND=noninteractive apt install -y make build-essential         wget flex bison unzip python-is-python3 python3-pip         ninja-build pkg-config libpixman-1-dev libglib2.0-dev git wget         curl libelf-dev libvirglrenderer-dev libepoxy-dev libgtk-3-dev         libgcrypt20-dev libgpg-error-dev libzip-dev bash coreutils         git git-lfs libncurses5 mingw-w64 msitools libz-mingw-w64-dev         pkg-config-mingw-w64-x86-64 zstd cmake wine &&     DEBIAN_FRONTEND=noninteractive apt build-dep -yy qemu\" did not complete successfully: exit code: 100" spanID=47d084a9ba624714 traceID=2f5ab7a485a1accdcc76c2b31848b824
        ------
         > [2/7] RUN cp /etc/apt/sources.list /etc/apt/sources.list~ &&     sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list &&     apt-get -y update &&     DEBIAN_FRONTEND=noninteractive apt install -y make build-essential         wget flex bison unzip python-is-python3 python3-pip         ninja-build pkg-config libpixman-1-dev libglib2.0-dev git wget         curl libelf-dev libvirglrenderer-dev libepoxy-dev libgtk-3-dev         libgcrypt20-dev libgpg-error-dev libzip-dev bash coreutils         git git-lfs libncurses5 mingw-w64 msitools libz-mingw-w64-dev         pkg-config-mingw-w64-x86-64 zstd cmake wine &&     DEBIAN_FRONTEND=noninteractive apt build-dep -yy qemu:
        0.992   404  Not Found [IP: 185.125.190.82 80]
        1.147 Err:7 http://archive.ubuntu.com/ubuntu lunar-updates Release
        1.147   404  Not Found [IP: 185.125.190.82 80]
        1.303 Err:8 http://archive.ubuntu.com/ubuntu lunar-backports Release
        1.303   404  Not Found [IP: 185.125.190.82 80]
        1.307 Reading package lists...
        1.317 E: The repository 'http://security.ubuntu.com/ubuntu lunar-security Release' does not have a Release file.
        1.317 E: The repository 'http://archive.ubuntu.com/ubuntu lunar Release' does not have a Release file.
        1.317 E: The repository 'http://archive.ubuntu.com/ubuntu lunar-updates Release' does not have a Release file.
        1.317 E: The repository 'http://archive.ubuntu.com/ubuntu lunar-backports Release' does not have a Release file.
        ------
        Dockerfile:3
        --------------------
           2 |
           3 | >>> RUN cp /etc/apt/sources.list /etc/apt/sources.list~ && \
           4 | >>>     sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list && \
           5 | >>>     apt-get -y update && \
           6 | >>>     DEBIAN_FRONTEND=noninteractive apt install -y make build-essential \
           7 | >>>         wget flex bison unzip python-is-python3 python3-pip \
           8 | >>>         ninja-build pkg-config libpixman-1-dev libglib2.0-dev git wget \
           9 | >>>         curl libelf-dev libvirglrenderer-dev libepoxy-dev libgtk-3-dev \
          10 | >>>         libgcrypt20-dev libgpg-error-dev libzip-dev bash coreutils \
          11 | >>>         git git-lfs libncurses5 mingw-w64 msitools libz-mingw-w64-dev \
          12 | >>>         pkg-config-mingw-w64-x86-64 zstd cmake wine && \
          13 | >>>     DEBIAN_FRONTEND=noninteractive apt build-dep -yy qemu
          14 |
        --------------------
         ERROR: failed to solve: process "/bin/sh -c cp /etc/apt/sources.list /etc/apt/sources.list~ &&     sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list &&     apt-get -y update &&     DEBIAN_FRONTEND=noninteractive apt install -y make build-essential         wget flex bison unzip python-is-python3 python3-pip         ninja-build pkg-config libpixman-1-dev libglib2.0-dev git wget         curl libelf-dev libvirglrenderer-dev libepoxy-dev libgtk-3-dev         libgcrypt20-dev libgpg-error-dev libzip-dev bash coreutils         git git-lfs libncurses5 mingw-w64 msitools libz-mingw-w64-dev         pkg-config-mingw-w64-x86-64 zstd cmake wine &&     DEBIAN_FRONTEND=noninteractive apt build-dep -yy qemu" did not complete successfully: exit code: 100
        2 warnings found (use docker --debug to expand):
         - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 28)
         - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 29)
        Cleaning up project directory and file based variables

Signed-off-by: Brian Cain <brian.cain@oss.qualcomm.com>