Use python3.8 with QEMU configure
QEMU no longer supports python3.6, giving the following error when we
run build-toolchain.sh:

ERROR: Cannot use '/usr/bin/python3.6', Python >= 3.7 is required.
       Use --python=/path/to/python to specify a supported Python.

So let's update to python3.8.

Signed-off-by: Matheus Tavares Bernardino <quic_mathbern@quicinc.com>